# ----------------------------------------------------
# This file should not be generated by the radium script
# ----------------------------------------------------

set(dataflow_rendering_sources Renderer/DataflowRenderer.cpp Renderer/RenderingGraph.cpp)

set(dataflow_rendering_headers Nodes/RenderingNode.hpp Renderer/DataflowRenderer.hpp
                               Renderer/RenderingGraph.hpp
)
