# ----------------------------------------------------
# This file should not be generated by the radium script
# ----------------------------------------------------

set(dataflow_rendering_sources
    Renderer/ControllableRenderer.cpp RenderingGraph.cpp Nodes/RenderingBuiltInsNodes.cpp
    Nodes/Sinks/DisplaySinkNode.cpp Nodes/Sources/TextureSourceNode.cpp
)

set(dataflow_rendering_headers
    Nodes/RenderingNode.hpp Renderer/ControllableRenderer.hpp Nodes/RenderingBuiltInsNodes.hpp
    RenderingGraph.hpp Nodes/Sources/Scene.hpp Nodes/Sinks/DisplaySinkNode.hpp
    Nodes/Sources/TextureSourceNode.hpp
)
