# ----------------------------------------------------
# This file should not be generated by the radium script
# ----------------------------------------------------

set(dataflow_rendering_sources
    Renderer/ControllableRenderer.cpp
    Renderer/RenderGraphController.cpp
    RenderingGraph.cpp
    Nodes/AntiAliasing/FxaaNode.cpp
    Nodes/RenderingBuiltInsNodes.cpp
    Nodes/Sinks/DisplaySinkNode.cpp
    Nodes/Sources/TextureSourceNode.cpp
    Nodes/RenderNodes/ClearColorNode.cpp
    Nodes/RenderNodes/EmissivityRenderNode.cpp
    Nodes/RenderNodes/EnvironmentLightingNode.cpp
    Nodes/RenderNodes/GeometryAovsNode.cpp
    Nodes/RenderNodes/LocalLightingNode.cpp
    Nodes/RenderNodes/SimpleRenderNode.cpp
    Nodes/RenderNodes/SsaoRenderNode.cpp
    Nodes/RenderNodes/TransparentLocalLightingNode.cpp
    Nodes/RenderNodes/VolumeLocalLightingNode.cpp
    Nodes/RenderNodes/WireframeRenderingNode.cpp
)

set(dataflow_rendering_headers
    Nodes/RenderingBuiltInsNodes.hpp
    Nodes/RenderingNode.hpp
    Nodes/AntiAliasing/FxaaNode.hpp
    Nodes/RenderNodes/ClearColorNode.hpp
    Nodes/RenderNodes/EmissivityRenderNode.hpp
    Nodes/RenderNodes/EnvironmentLightingNode.hpp
    Nodes/RenderNodes/GeometryAovsNode.hpp
    Nodes/RenderNodes/LocalLightingNode.hpp
    Nodes/RenderNodes/SimpleRenderNode.hpp
    Nodes/RenderNodes/SsaoRenderNode.hpp
    Nodes/RenderNodes/TransparentLocalLightingNode.hpp
    Nodes/RenderNodes/VolumeLocalLightingNode.hpp
    Nodes/RenderNodes/WireframeRenderingNode.hpp
    Nodes/Sinks/DisplaySinkNode.hpp
    Nodes/Sources/Scene.hpp
    Nodes/Sources/EnvMapSourceNode.hpp
    Nodes/Sources/TextureSourceNode.hpp
    Renderer/ControllableRenderer.hpp
    Renderer/RenderGraphController.hpp
    RenderingGraph.hpp
)

set(dataflow_rendering_resources Shaders)
