# https://github.com/DavidAnson/markdownlint/blob/main/schema/.markdownlint.yaml
default: true
MD002: false
MD033: false

MD013:
  line_length: 520
MD034: false
MD041: false
# link fragments from php markdown are not recognized
MD051: false
