language: cpp
dist: xenial
sudo: true

script:
  - make -j 4
  - make check
  - |
    if [ "$BUILD_DOC" = "On" ]; then
        make RadiumDoc
    fi;

notifications:
   slack: storm-cg:oxJ5LToK0qfPBkNW0Hus3TQg

cache:
  directories:

env:
  global:
    - OMP_NUM_THREADS=4
    - TIMEOUT=1000


before_install:
  - export CHECKOUT_PATH=`pwd`;
  - eval "${MATRIX_EVAL}"
  - if [ -n "$GCC_VERSION" ]; then export CXX="g++-${GCC_VERSION}" CC="gcc-${GCC_VERSION}"; fi
  - if [ -n "$CLANG_VERSION" ]; then export CXX="clang++-${CLANG_VERSION}" CC="clang-${CLANG_VERSION}"; fi
  - $CXX --version
  - cmake --version


matrix:
  include:
    # mac clang Release
    - env:
        - BUILD_TYPE=Release
        - BUILD_DOC=Off
        - MATRIX_EVAL=""
      os: osx
      compiler: clang

    # linx clang Release
    - env:
        - BUILD_TYPE=Release
        - CLANG_VERSION=5.0
        - BUILD_DOC=Off
        - MATRIX_EVAL=""
      os: linux
      addons: &clang50
        apt:
          packages:
            - util-linux
            - clang-5.0
            - g++-7
            - cmake
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-xenial-5.0

    # linx gcc Release
    - env:
        - BUILD_TYPE=Release
        - GCC_VERSION=7
        - BUILD_DOC=On
        - MATRIX_EVAL=""
      os: linux
      addons: &gcc7
        apt:
          packages:
            - g++-7
            - cmake
            - doxygen
            - graphviz
          sources:
            - ubuntu-toolchain-r-test


install:
  - cd $CHECKOUT_PATH

  - mkdir -p build
  - cd build
  - cmake .. -DCMAKE_C_COMPILER=$CC -DCMAKE_CXX_COMPILER=$CXX -DCMAKE_BUILD_TYPE=${BUILD_TYPE}


# safelist
branches:
  except:
  - gh-pages

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: build/doc/html/
  github_token: $GITHUB_API_KEY
  on:
    branch: master
    condition: "$BUILD_DOC = On"

