language: cpp

script:
  - make -j 4

cache:
  directories:
    - ${TRAVIS_BUILD_DIR}/cmake3.3
    - ~/Qt/5.10.0

env:
  global:
    - OMP_NUM_THREADS=4
    - TIMEOUT=1000


before_install:
  - export CHECKOUT_PATH=`pwd`;
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew update && brew install gnu-which --with-default-names && brew install qt; fi
  - if [ -n "$GCC_VERSION" ]; then export CXX="g++-${GCC_VERSION}" CC="gcc-${GCC_VERSION}"; fi
  - if [ -n "$CLANG_VERSION" ]; then export CXX="clang++-${CLANG_VERSION}" CC="clang-${CLANG_VERSION}"; fi
  - which $CXX
  - which $CC
  - $CXX --version

  ############################################################################
  # Install a recent CMake
  ############################################################################
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      # remove existing cmake install
      sudo apt-get remove -qq cmake cmake-data

      CMAKE_URL="https://www.cmake.org/files/v3.3/cmake-3.3.1-Linux-x86_64.tar.gz"
      mkdir cmake3.3 && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake3.3
      export PATH=${PWD}/cmake3.3/bin:${PATH}
    fi
  - cmake --version

  ############################################################################
  # Install a recent Qt
  ############################################################################
  - |
    if [ "$TRAVIS_OS_NAME" = "linux" ]; then
      if [ ! -d "~/Qt/5.10.0/gcc_64" ]; then
        wget http://download.qt.io/official_releases/online_installers/qt-unified-linux-x64-online.run ;
        chmod a+x ./qt-unified-linux-x64-online.run ;
        export QT_QPA_PLATFORM=minimal ;
        travis_wait 60 ./qt-unified-linux-x64-online.run --script .ci/qt-installer-noninteractive.qs --no-force-installations --verbose ;
      fi;
    fi;


matrix:
  include:
    # mac clang Release
    - env:
        - BUILD_TYPE=Release
        - PREFIX_PATH="/usr/local/Cellar/qt/5.10.0_1"
      os: osx
      compiler: clang

    # linx clang Release
    - env:
        - BUILD_TYPE=Release
        - PREFIX_PATH="~/Qt/5.10.0/gcc_64/lib/cmake"
        - CLANG_VERSION=5.0
      os: linux
      addons: &clang50
        apt:
          packages:
            - util-linux
            - clang-5.0
            - g++-7
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-5.0

    # linx gcc Release
    - env:
        - BUILD_TYPE=Release
        - PREFIX_PATH="~/Qt/5.10.0/gcc_64/lib/cmake"
        - GCC_VERSION=7
      os: linux
      addons: &gcc7
        apt:
          packages:
            - g++-7
          sources:
            - ubuntu-toolchain-r-test


install:
  - cd $CHECKOUT_PATH

  - mkdir -p build
  - cd build
  - cmake .. -DRADIUM_WITH_OMP=True -DCMAKE_C_COMPILER=$CC -DCMAKE_CXX_COMPILER=$CXX -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DCMAKE_PREFIX_PATH=${PREFIX_PATH}


# safelist
branches:
  except:
  - gh-pages


