language: cpp
sudo: true

script:
  - make -j 4
  - |
    if [ "$TRAVIS_OS_NAME" = "osx" ]; then
      cd ../Bundle-Clang/Release/bin/
      otool -L ./main-app
    fi;

notifications:
   slack: storm-cg:oxJ5LToK0qfPBkNW0Hus3TQg

cache:
  directories:

env:
  global:
    - OMP_NUM_THREADS=4
    - TIMEOUT=1000


before_install:
  - export CHECKOUT_PATH=`pwd`;
  - |
    if [ "$TRAVIS_OS_NAME" == "osx" ]; then
        #attempt to fix SSL issue with Qt:
        # ==> Downloading https://homebrew.bintray.com/bottles/qt-5.10.1.sierra.bottle.tar.gz
        # curl: (56) SSLRead() return error -9806
        # Error: Failed to download resource "qt"
        #
        # Source:
        # https://gist.github.com/entropiae/a899d8a78dc8a38f505e
        brew remove curl
        brew install openssl
        brew install --with-openssl curl
        brew install --with-curl --with-openssl qt
        brew install gnu-which --with-default-names
    fi;
  - if [ -n "$GCC_VERSION" ]; then export CXX="g++-${GCC_VERSION}" CC="gcc-${GCC_VERSION}"; fi
  - if [ -n "$CLANG_VERSION" ]; then export CXX="clang++-${CLANG_VERSION}" CC="clang-${CLANG_VERSION}"; fi
  - which $CXX
  - which $CC
  - $CXX --version

  ############################################################################
  # Install a recent CMake
  ############################################################################
  #- |
  #  if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
  #    # remove existing cmake install
  #    sudo apt-get remove -qq cmake cmake-data
  #
  #    CMAKE_URL="https://www.cmake.org/files/v3.3/cmake-3.3.1-Linux-x86_64.tar.gz"
  #    mkdir cmake3.3 && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake3.3
  #    export PATH=${PWD}/cmake3.3/bin:${PATH}
  #  fi
  - cmake --version

  ############################################################################
  # Install a recent Qt
  ############################################################################
  - |
    if [ "$TRAVIS_OS_NAME" = "linux" ]; then
      sudo add-apt-repository --yes ppa:beineri/opt-qt-5.10.1-trusty
      sudo apt-get --yes update
      sudo apt-get --yes install qt510-meta-minimal qt510svg
      source /opt/qt510/bin/qt510-env.sh # see https://launchpad.net/~beineri/+archive/ubuntu/opt-qt-5.10.1-trusty


      #if [ ! -d "~/Qt/5.10.1/gcc_64" ]; then
      #  # wget http://download.qt.io/official_releases/online_installers/qt-unified-linux-x64-online.run ;
      #  TRAVIS_URL="https://download.qt.io/official_releases/qt/5.10/5.10.1/qt-opensource-linux-x64-5.10.1.run"
      #  export QT_QPA_PLATFORM=minimal ;
      #  travis_retry wget ${TRAVIS_URL} &&  chmod a+x ./qt-opensource-linux-x64-5.10.1.run && ./qt-opensource-linux-x64-5.10.1.run --script .ci/qt-installer-noninteractive.qs --no-force-installations --verbose ;
      #fi;
    fi;


matrix:
  include:
    # mac clang Release
    - env:
        - BUILD_TYPE=Release
        - PREFIX_PATH="/usr/local/opt/qt/lib/cmake"
      os: osx
      compiler: clang

    # linx clang Release
    - env:
        - BUILD_TYPE=Release
        - PREFIX_PATH="~/Qt/5.10.0/gcc_64/lib/cmake"
        - CLANG_VERSION=5.0
      os: linux
      addons: &clang50
        apt:
          packages:
            - util-linux
            - clang-5.0
            - g++-7
            - cmake3
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-5.0

    # linx gcc Release
    - env:
        - BUILD_TYPE=Release
        - PREFIX_PATH="~/Qt/5.10.0/gcc_64/lib/cmake"
        - GCC_VERSION=7
      os: linux
      addons: &gcc7
        apt:
          packages:
            - g++-7
            - cmake3
          sources:
            - ubuntu-toolchain-r-test


install:
  - cd $CHECKOUT_PATH

  - mkdir -p build
  - cd build
  - cmake .. -DRADIUM_WITH_OMP=True -DCMAKE_C_COMPILER=$CC -DCMAKE_CXX_COMPILER=$CXX -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DCMAKE_PREFIX_PATH=${PREFIX_PATH}


# safelist
branches:
  except:
  - gh-pages


