#ifndef RADIUMENGINE_KEYBOARD_HPP
#define RADIUMENGINE_KEYBOARD_HPP

namespace Ra
{
    namespace Gui
    {
        enum Key
        {
            Key_Unknown = -1,
            Key_A = 0,
            Key_B,
            Key_C,
            Key_D,
            Key_E,
            Key_F,
            Key_G,
            Key_H,
            Key_I,
            Key_J,
            Key_K,
            Key_L,
            Key_M,
            Key_N,
            Key_O,
            Key_P,
            Key_Q,
            Key_R,
            Key_S,
            Key_T,
            Key_U,
            Key_V,
            Key_W,
            Key_X,
            Key_Y,
            Key_Z,
            Key_Num0,
            Key_Num1,
            Key_Num2,
            Key_Num3,
            Key_Num4,
            Key_Num5,
            Key_Num6,
            Key_Num7,
            Key_Num8,
            Key_Num9,
            Key_Escape,
            Key_LControl,
            Key_LShift,
            Key_LAlt,
            Key_LSystem,
            Key_RControl,
            Key_RShift,
            Key_RAlt,
            Key_RSystem,
            Key_Menu,
            Key_LBracket,
            Key_RBracket,
            Key_SemiColon,
            Key_Comma,
            Key_Period,
            Key_Quote,
            Key_Slash,
            Key_BackSlash,
            Key_Tilde,
            Key_Equal,
            Key_Dash,
            Key_Space,
            Key_Return,
            Key_BackSpace,
            Key_Tab,
            Key_PageUp,
            Key_PageDown,
            Key_End,
            Key_Home,
            Key_Insert,
            Key_Delete,
            Key_Add,
            Key_Subtract,
            Key_Multiply,
            Key_Divide,
            Key_Left,
            Key_Right,
            Key_Up,
            Key_Down,
            Key_Numpad0,
            Key_Numpad1,
            Key_Numpad2,
            Key_Numpad3,
            Key_Numpad4,
            Key_Numpad5,
            Key_Numpad6,
            Key_Numpad7,
            Key_Numpad8,
            Key_Numpad9,
            Key_F1,
            Key_F2,
            Key_F3,
            Key_F4,
            Key_F5,
            Key_F6,
            Key_F7,
            Key_F8,
            Key_F9,
            Key_F10,
            Key_F11,
            Key_F12,
            Key_F13,
            Key_F14,
            Key_F15,
            Key_Pause,

            Key_KeyCount,
        };

        extern bool isKeyPressed( Key key );
    } // namespace Gui
} // namespace Ra

#endif // RADIUMENGINE_KEYBOARD_HPP
