#include "Version.hpp"
/* This file is automatically generated     * 
 * see CMakeGenerateVersion.txt for details   */

const char* Ra::Version::compiler = "/usr/bin/g++ 5.4.1";
const char* Ra::Version::compileFlags = "-Wall -Wextra  -pthread -msse3 -Wno-sign-compare -Wno-unused-parameter -fno-exceptions -fPIC    -DQT_COMPILING_QSTRING_COMPAT_CPP"
#if defined CORE_DEBUG
"-D_DEBUG -DCORE_DEBUG -g3 -ggdb -g";
#else
"-DNDEBUG -O3 -mfpmath=sse -ffast-math";
#endif
const char* Ra::Version::compileDate = __DATE__; 
const char* Ra::Version::compileTime = __TIME__; 
