var dir_83737572142744a1a1847d83d6fd2bde =
[
    [ "deprecated", "dir_39ca1dd2996543bff2d1524dc7d43ff3.html", "dir_39ca1dd2996543bff2d1524dc7d43ff3" ],
    [ "AbstractGeometry.hpp", "AbstractGeometry_8hpp_source.html", null ],
    [ "CatmullClarkSubdivider.cpp", "CatmullClarkSubdivider_8cpp_source.html", null ],
    [ "CatmullClarkSubdivider.hpp", "CatmullClarkSubdivider_8hpp_source.html", null ],
    [ "Curve2D.hpp", "Curve2D_8hpp_source.html", null ],
    [ "DistanceQueries.hpp", "DistanceQueries_8hpp_source.html", null ],
    [ "IndexedGeometry.cpp", "IndexedGeometry_8cpp_source.html", null ],
    [ "IndexedGeometry.hpp", "IndexedGeometry_8hpp_source.html", null ],
    [ "LoopSubdivider.cpp", "LoopSubdivider_8cpp_source.html", null ],
    [ "LoopSubdivider.hpp", "LoopSubdivider_8hpp_source.html", null ],
    [ "MeshPrimitives.cpp", "MeshPrimitives_8cpp_source.html", null ],
    [ "MeshPrimitives.hpp", "MeshPrimitives_8hpp_source.html", null ],
    [ "Obb.hpp", "Obb_8hpp_source.html", null ],
    [ "OpenMesh.hpp", "OpenMesh_8hpp_source.html", null ],
    [ "PolyLine.cpp", "PolyLine_8cpp_source.html", null ],
    [ "PolyLine.hpp", "PolyLine_8hpp_source.html", null ],
    [ "RayCast.cpp", "RayCast_8cpp_source.html", null ],
    [ "RayCast.hpp", "RayCast_8hpp_source.html", null ],
    [ "Spline.hpp", "Spline_8hpp_source.html", null ],
    [ "StandardAttribNames.hpp", "StandardAttribNames_8hpp_source.html", null ],
    [ "TopologicalMesh.cpp", "TopologicalMesh_8cpp_source.html", null ],
    [ "TopologicalMesh.hpp", "TopologicalMesh_8hpp_source.html", null ],
    [ "TriangleMesh.cpp", "TriangleMesh_8cpp_source.html", null ],
    [ "TriangleMesh.hpp", "TriangleMesh_8hpp_source.html", null ],
    [ "Volume.cpp", "Volume_8cpp_source.html", null ],
    [ "Volume.hpp", "Volume_8hpp_source.html", null ]
];