var namespaceCLI =
[
    [ "detail", "namespaceCLI_1_1detail.html", "namespaceCLI_1_1detail" ],
    [ "App", "classCLI_1_1App.html", "classCLI_1_1App" ],
    [ "ArgumentMismatch", "classCLI_1_1ArgumentMismatch.html", null ],
    [ "AsNumberWithUnit", "classCLI_1_1AsNumberWithUnit.html", "classCLI_1_1AsNumberWithUnit" ],
    [ "AsSizeValue", "classCLI_1_1AsSizeValue.html", "classCLI_1_1AsSizeValue" ],
    [ "AutoTimer", "classCLI_1_1AutoTimer.html", "classCLI_1_1AutoTimer" ],
    [ "BadNameString", "classCLI_1_1BadNameString.html", null ],
    [ "Bound", "classCLI_1_1Bound.html", "classCLI_1_1Bound" ],
    [ "CallForAllHelp", "classCLI_1_1CallForAllHelp.html", null ],
    [ "CallForHelp", "classCLI_1_1CallForHelp.html", null ],
    [ "CallForVersion", "classCLI_1_1CallForVersion.html", null ],
    [ "CheckedTransformer", "classCLI_1_1CheckedTransformer.html", "classCLI_1_1CheckedTransformer" ],
    [ "Config", "classCLI_1_1Config.html", "classCLI_1_1Config" ],
    [ "ConfigBase", "classCLI_1_1ConfigBase.html", "classCLI_1_1ConfigBase" ],
    [ "ConfigError", "classCLI_1_1ConfigError.html", null ],
    [ "ConfigINI", "classCLI_1_1ConfigINI.html", "classCLI_1_1ConfigINI" ],
    [ "ConfigItem", "structCLI_1_1ConfigItem.html", "structCLI_1_1ConfigItem" ],
    [ "ConstructionError", "classCLI_1_1ConstructionError.html", null ],
    [ "ConversionError", "classCLI_1_1ConversionError.html", null ],
    [ "CustomValidator", "classCLI_1_1CustomValidator.html", null ],
    [ "Error", "classCLI_1_1Error.html", "classCLI_1_1Error" ],
    [ "ExcludesError", "classCLI_1_1ExcludesError.html", null ],
    [ "ExtrasError", "classCLI_1_1ExtrasError.html", null ],
    [ "FileError", "classCLI_1_1FileError.html", null ],
    [ "Formatter", "classCLI_1_1Formatter.html", "classCLI_1_1Formatter" ],
    [ "FormatterBase", "classCLI_1_1FormatterBase.html", "classCLI_1_1FormatterBase" ],
    [ "FormatterLambda", "classCLI_1_1FormatterLambda.html", "classCLI_1_1FormatterLambda" ],
    [ "HorribleError", "classCLI_1_1HorribleError.html", null ],
    [ "IncorrectConstruction", "classCLI_1_1IncorrectConstruction.html", null ],
    [ "InvalidError", "classCLI_1_1InvalidError.html", null ],
    [ "is_bool", "structCLI_1_1is__bool.html", null ],
    [ "is_bool< bool >", "structCLI_1_1is__bool_3_01bool_01_4.html", null ],
    [ "is_copyable_ptr", "structCLI_1_1is__copyable__ptr.html", "structCLI_1_1is__copyable__ptr" ],
    [ "is_shared_ptr", "structCLI_1_1is__shared__ptr.html", null ],
    [ "is_shared_ptr< const std::shared_ptr< T > >", "structCLI_1_1is__shared__ptr_3_01const_01std_1_1shared__ptr_3_01T_01_4_01_4.html", null ],
    [ "is_shared_ptr< std::shared_ptr< T > >", "structCLI_1_1is__shared__ptr_3_01std_1_1shared__ptr_3_01T_01_4_01_4.html", null ],
    [ "IsMember", "classCLI_1_1IsMember.html", "classCLI_1_1IsMember" ],
    [ "IsMemberType", "structCLI_1_1IsMemberType.html", "structCLI_1_1IsMemberType" ],
    [ "IsMemberType< const char * >", "structCLI_1_1IsMemberType_3_01const_01char_01_5_01_4.html", "structCLI_1_1IsMemberType_3_01const_01char_01_5_01_4" ],
    [ "make_void", "structCLI_1_1make__void.html", "structCLI_1_1make__void" ],
    [ "Option", "classCLI_1_1Option.html", "classCLI_1_1Option" ],
    [ "Option_group", "classCLI_1_1Option__group.html", "classCLI_1_1Option__group" ],
    [ "OptionAlreadyAdded", "classCLI_1_1OptionAlreadyAdded.html", null ],
    [ "OptionBase", "classCLI_1_1OptionBase.html", "classCLI_1_1OptionBase" ],
    [ "OptionDefaults", "classCLI_1_1OptionDefaults.html", "classCLI_1_1OptionDefaults" ],
    [ "OptionNotFound", "classCLI_1_1OptionNotFound.html", null ],
    [ "ParseError", "classCLI_1_1ParseError.html", null ],
    [ "Range", "classCLI_1_1Range.html", "classCLI_1_1Range" ],
    [ "RequiredError", "classCLI_1_1RequiredError.html", null ],
    [ "RequiresError", "classCLI_1_1RequiresError.html", null ],
    [ "RuntimeError", "classCLI_1_1RuntimeError.html", null ],
    [ "Success", "classCLI_1_1Success.html", null ],
    [ "Timer", "classCLI_1_1Timer.html", "classCLI_1_1Timer" ],
    [ "Transformer", "classCLI_1_1Transformer.html", "classCLI_1_1Transformer" ],
    [ "TypeValidator", "classCLI_1_1TypeValidator.html", "classCLI_1_1TypeValidator" ],
    [ "ValidationError", "classCLI_1_1ValidationError.html", null ],
    [ "Validator", "classCLI_1_1Validator.html", "classCLI_1_1Validator" ]
];