# ----------------------------------------------------
# This file should not be generated by the radium script
# ----------------------------------------------------

set(dataflow_qtgui_sources GraphEditor/GraphEditorView.cpp GraphEditor/NodeAdapterModel.cpp
                           GraphEditor/GraphEditorWindow.cpp GraphEditor/WidgetFactory.cpp
)

set(dataflow_qtgui_headers
    GraphEditor/ConnectionStatusData.hpp GraphEditor/GraphEditorView.hpp
    GraphEditor/GraphEditorWindow.hpp GraphEditor/NodeAdapterModel.hpp
    GraphEditor/WidgetFactory.hpp
)

set(dataflow_qtgui_resources GraphEditor/GraphEditor.qrc)
