# ----------------------------------------------------
# This file can be generated from a script:
# To do so, run "./generateFilelistForModule.sh Core"
# from ./scripts directory
# ----------------------------------------------------

set(core_sources
    Animation/Cage.cpp
    Animation/DualQuaternionSkinning.cpp
    Animation/HandleArray.cpp
    Animation/HandleWeightOperation.cpp
    Animation/LinearBlendSkinning.cpp
    Animation/PoseOperation.cpp
    # Animation/RotationCenterSkinning.cpp
    Animation/Sequence.cpp
    Animation/Skeleton.cpp
    Asset/AnimationData.cpp
    Asset/BlinnPhongMaterialData.cpp
    Asset/Camera.cpp
    Asset/FileData.cpp
    Asset/GeometryData.cpp
    Asset/HandleData.cpp
    Asset/HandleToSkeleton.cpp
    Asset/LightData.cpp
    Asset/MaterialData.cpp
    Containers/AdjacencyList.cpp
    Containers/VariableSet.cpp
    Geometry/CatmullClarkSubdivider.cpp
    Geometry/Curve2D.cpp
    Geometry/IndexedGeometry.cpp
    Geometry/LoopSubdivider.cpp
    Geometry/MeshPrimitives.cpp
    Geometry/PolyLine.cpp
    Geometry/RayCast.cpp
    Geometry/TopologicalMesh.cpp
    Geometry/TriangleMesh.cpp
    Geometry/Volume.cpp
    Geometry/deprecated/TopologicalMesh.cpp
    Resources/Resources.cpp
    Tasks/TaskQueue.cpp
    Utils/Attribs.cpp
    Utils/CircularIndex.cpp
    Utils/Color.cpp
    Utils/StackTrace.cpp
    Utils/StringUtils.cpp
)

set(core_headers
    Animation/Cage.hpp
    Animation/DualQuaternionSkinning.hpp
    Animation/HandleArray.hpp
    Animation/HandleWeight.hpp
    Animation/HandleWeightOperation.hpp
    Animation/KeyFramedValue.hpp
    Animation/KeyFramedValueController.hpp
    Animation/KeyFramedValueInterpolators.hpp
    Animation/LinearBlendSkinning.hpp
    Animation/Pose.hpp
    Animation/PoseOperation.hpp
    # Animation/RotationCenterSkinning.hpp
    Animation/Sequence.hpp
    Animation/Skeleton.hpp
    Animation/SkinningData.hpp
    Asset/AnimationData.hpp
    Asset/AnimationTime.hpp
    Asset/AssetData.hpp
    Asset/BlinnPhongMaterialData.hpp
    Asset/Camera.hpp
    Asset/DataLoader.hpp
    Asset/FileData.hpp
    Asset/FileLoaderInterface.hpp
    Asset/GeometryData.hpp
    Asset/HandleData.hpp
    Asset/HandleToSkeleton.hpp
    Asset/LightData.hpp
    Asset/MaterialData.hpp
    Asset/VolumeData.hpp
    Containers/AdjacencyList.hpp
    Containers/AlignedAllocator.hpp
    Containers/AlignedStdVector.hpp
    Containers/Grid.hpp
    Containers/Iterators.hpp
    Containers/MakeShared.hpp
    Containers/Tex.hpp
    Containers/VariableSet.hpp
    Containers/VectorArray.hpp
    CoreMacros.hpp
    Geometry/AbstractGeometry.hpp
    Geometry/CatmullClarkSubdivider.hpp
    Geometry/Curve2D.hpp
    Geometry/DistanceQueries.hpp
    Geometry/IndexedGeometry.hpp
    Geometry/LoopSubdivider.hpp
    Geometry/MeshPrimitives.hpp
    Geometry/Obb.hpp
    Geometry/OpenMesh.hpp
    Geometry/PolyLine.hpp
    Geometry/RayCast.hpp
    Geometry/Spline.hpp
    Geometry/StandardAttribNames.hpp
    Geometry/TopologicalMesh.hpp
    Geometry/TriangleMesh.hpp
    Geometry/Volume.hpp
    Geometry/deprecated/TopologicalMesh.hpp
    Math/DualQuaternion.hpp
    Math/Interpolation.hpp
    Math/LinearAlgebra.hpp
    Math/Math.hpp
    Math/Quadric.hpp
    RaCore.hpp
    Resources/Resources.hpp
    Tasks/Task.hpp
    Tasks/TaskQueue.hpp
    Types.hpp
    Utils/Attribs.hpp
    Utils/BijectiveAssociation.hpp
    Utils/Chronometer.hpp
    Utils/CircularIndex.hpp
    Utils/Color.hpp
    Utils/ContainerIntrospectionInterface.hpp
    Utils/EnumConverter.hpp
    Utils/Index.hpp
    Utils/IndexMap.hpp
    Utils/IndexedObject.hpp
    Utils/Log.hpp
    Utils/ObjectWithSemantic.hpp
    Utils/Observable.hpp
    Utils/Singleton.hpp
    Utils/StackTrace.hpp
    Utils/StdExperimentalTypeTraits.hpp
    Utils/StdFilesystem.hpp
    Utils/StdMapIterators.hpp
    Utils/StdOptional.hpp
    Utils/StdUtils.hpp
    Utils/StringUtils.hpp
    Utils/Timer.hpp
    Utils/TypesUtils.hpp
    Utils/Version.hpp
)
