#ifndef RADIUMENGINE_RENDEROBJECTTYPES_HPP
#define RADIUMENGINE_RENDEROBJECTTYPES_HPP

namespace Ra::Engine {

/**
 * Defines the families of objects for rendering.
 */
enum class RenderObjectType {
    /// "Ui" render objects are drawn on top of everything else and view independent
    UI = 0,
    /// "Debug" render objects are drawn like any other object (not lit though)
    Debug,
    /// "Geometry" render objects are those loaded using Radium::IO and generated by GeometrySystem
    Geometry,

    Count
};

} // namespace Ra::Engine
#endif // RADIUMENGINE_RENDEROBJECT_TYPES
