
set( engine_sources
    Component/Component.cpp
    Component/GeometryComponent.cpp
    Entity/Entity.cpp
    ItemModel/ItemEntry.cpp
    Managers/CameraManager/CameraManager.cpp
    Managers/CameraManager/DefaultCameraManager.cpp
    Managers/ComponentMessenger/ComponentMessenger.cpp
    Managers/EntityManager/EntityManager.cpp
    Managers/LightManager/DefaultLightManager.cpp
    Managers/LightManager/LightManager.cpp
    Managers/SignalManager/SignalManager.cpp
    Managers/SystemDisplay/SystemDisplay.cpp
    RadiumEngine.cpp
    Renderer/Camera/Camera.cpp
    Renderer/Light/DirLight.cpp
    Renderer/Light/Light.cpp
    Renderer/Light/PointLight.cpp
    Renderer/Light/SpotLight.cpp
    Renderer/Material/BlinnPhongMaterial.cpp
    Renderer/Material/Material.cpp
    Renderer/Material/MaterialConverters.cpp
    Renderer/Mesh/Mesh.cpp
    Renderer/RenderObject/Primitives/DrawPrimitives.cpp
    Renderer/RenderObject/RenderObject.cpp
    Renderer/RenderObject/RenderObjectManager.cpp
    Renderer/RenderTechnique/RenderParameters.cpp
    Renderer/RenderTechnique/RenderTechnique.cpp
    Renderer/RenderTechnique/ShaderConfigFactory.cpp
    Renderer/RenderTechnique/ShaderConfiguration.cpp
    Renderer/RenderTechnique/ShaderProgram.cpp
    Renderer/RenderTechnique/ShaderProgramManager.cpp
    Renderer/Renderer.cpp
    Renderer/Renderers/DebugRender.cpp
    Renderer/Renderers/ForwardRenderer.cpp
    Renderer/Texture/Texture.cpp
    Renderer/Texture/TextureManager.cpp
    System/GeometrySystem.cpp
    System/System.cpp
    System/TimedSystem.cpp
    RadiumEngine.cpp
    )

set( engine_headers
    Component/Component.hpp
    Component/GeometryComponent.hpp
    Entity/Entity.hpp
    FrameInfo.hpp
    ItemModel/ItemEntry.hpp
    Managers/CameraManager/CameraManager.hpp
    Managers/CameraManager/CameraStorage.hpp
    Managers/CameraManager/DefaultCameraManager.hpp
    Managers/ComponentMessenger/ComponentMessenger.hpp
    Managers/EntityManager/EntityManager.hpp
    Managers/LightManager/DefaultLightManager.hpp
    Managers/LightManager/LightManager.hpp
    Managers/LightManager/LightStorage.hpp
    Managers/SignalManager/SignalManager.hpp
    Managers/SystemDisplay/SystemDisplay.hpp
    RaEngine.hpp
    RadiumEngine.hpp
    Renderer/Camera/Camera.hpp
    Renderer/Displayable/DisplayableObject.hpp
    Renderer/Light/DirLight.hpp
    Renderer/Light/Light.hpp
    Renderer/Light/PointLight.hpp
    Renderer/Light/SpotLight.hpp
    Renderer/Material/BlinnPhongMaterial.hpp
    Renderer/Material/Material.hpp
    Renderer/Material/MaterialConverters.hpp
    Renderer/Mesh/Mesh.hpp
    Renderer/OpenGL/OpenGL.hpp
    Renderer/RenderObject/Primitives/DrawPrimitives.hpp
    Renderer/RenderObject/RenderObject.hpp
    Renderer/RenderObject/RenderObjectManager.hpp
    Renderer/RenderObject/RenderObjectTypes.hpp
    Renderer/RenderTechnique/RenderParameters.hpp
    Renderer/RenderTechnique/RenderTechnique.hpp
    Renderer/RenderTechnique/ShaderConfigFactory.hpp
    Renderer/RenderTechnique/ShaderConfiguration.hpp
    Renderer/RenderTechnique/ShaderProgram.hpp
    Renderer/RenderTechnique/ShaderProgramManager.hpp
    Renderer/Renderer.hpp
    Renderer/Renderers/DebugRender.hpp
    Renderer/Renderers/ForwardRenderer.hpp
    Renderer/Texture/Texture.hpp
    Renderer/Texture/TextureManager.hpp
    System/CouplingSystem.hpp
    System/GeometrySystem.hpp
    System/System.hpp
    System/TimedSystem.hpp
    FrameInfo.hpp
    RadiumEngine.hpp
    RaEngine.hpp
    )

set( engine_inlines
    Component/Component.inl
    Entity/Entity.inl
    ItemModel/ItemEntry.inl
    Managers/ComponentMessenger/ComponentMessenger.inl
    Renderer/Camera/Camera.inl
    Renderer/Light/DirLight.inl
    Renderer/Light/Light.inl
    Renderer/Light/PointLight.inl
    Renderer/Light/SpotLight.inl
    Renderer/Material/BlinnPhongMaterial.inl
    Renderer/Material/Material.inl
    Renderer/Mesh/Mesh.inl
    Renderer/RenderTechnique/RenderParameters.inl
    )

set( engine_shaders
    PointCloud.geom.glsl
    Helpers.glsl
    Structs.glsl
    Tonemap.glsl
    LightingFunctions.glsl
    Lights/DefaultLight.glsl
    Transform/TransformStructs.glsl
    Default.vert.glsl
    Default.frag.glsl
    Plain.vert.glsl
    Plain.frag.glsl
    Lines.vert.glsl
    Lines.frag.glsl
    Materials/BlinnPhong/BlinnPhongMaterial.glsl
    Materials/BlinnPhong/BlinnPhong.vert.glsl
    Materials/BlinnPhong/BlinnPhong.frag.glsl
    Materials/BlinnPhong/DepthAmbientBlinnPhong.frag.glsl
    Materials/BlinnPhong/LitOITBlinnPhong.frag.glsl
    Basic2D.vert.glsl
    DrawScreen.frag.glsl
    DrawScreenI.frag.glsl
    CircleBrush.frag.glsl
    DepthDisplay/DepthDisplay.frag.glsl
    Picking.vert.glsl
    PickingPoints.geom.glsl
    PickingLines.geom.glsl
    PickingLinesAdjacency.geom.glsl
    PickingTriangles.geom.glsl
    Picking.frag.glsl
    HdrToLdr/Hdr2Ldr.vert.glsl
    HdrToLdr/Hdr2Ldr.frag.glsl
    ComposeOIT.frag.glsl
    )
