# - Try to find glbinding
# Once done, this will define
#
# GLBINDING_FOUND - system has Assimp
# GLBINDING_INCLUDE_DIR - the Assimp include directories
# GLBINDING_LIBRARIES - link these to use Assimp

FIND_PATH( GLBINDING_INCLUDE_DIR NAMES glbinding/glbinding_features.h
  PATHS
  ${GLBINDING_DIR}
  /usr/include
  /usr/local/include
  /opt/local/include
)

FIND_LIBRARY( GLBINDING_LIBRARY
  NAMES glbinding
  PATHS
  ${GLBINDING_DIR}
  /usr/lib64
  /usr/lib
  /usr/local/lib
  /opt/local/lib
)

SET( GLBINDING_FOUND FALSE )
IF(GLBINDING_INCLUDE_DIR AND GLBINDING_LIBRARY)
  SET( GLBINDING_FOUND TRUE )
  SET( GLBINDING_LIBRARIES ${GLBINDING_LIBRARY} )
ENDIF(GLBINDING_INCLUDE_DIR AND GLBINDING_LIBRARY)

SET(GLBINDING_FIND_QUIETLY FALSE)
IF(GLBINDING_FOUND)
   IF(NOT GLBINDING_FIND_QUIETLY)
      MESSAGE(STATUS "Found glbinding: ${GLBINDING_LIBRARY}")
   ENDIF(NOT GLBINDING_FIND_QUIETLY)
ELSE(GLBINDING_FOUND)
   IF(GLBINDING_FIND_REQUIRED)
      MESSAGE(FATAL_ERROR "Could not find libglbinding")
   ENDIF(GLBINDING_FIND_REQUIRED)
ENDIF(GLBINDING_FOUND)
