name: build
# This workflow builds radium lib

# TRIGGERED BY
# - push-master-ci.yml
# - push-rc-ci.yml

defaults:
  run:
    shell: bash

on:
  workflow_call:
    secrets:
      GIST_BADGES_TOKEN:
        required: false
      GIST_BADGES_SECRET:
        required: false
      CODECOV_TOKEN:
        required: false
    inputs:
      use-double:
        required: false
        # boolean are not well handled https://github.com/actions/runner/issues/1483
        type: string
        default: "false"
      windows:
        required: false
        type: string
        default: "true"
      macos:
        required: false
        type: string
        default: "true"
      linux:
        required: false
        type: string
        default: "true"
      build-release:
        required: false
        type: string
        default: "true"
      build-debug:
        required: false
        type: string
        default: "true"
      coverage:
        required: false
        type: string
        default: "false"
      generate-badges:
        required: false
        type: string
        default: "false"

env:
  install_prefix: install
  build_prefix: build
  src_prefix:  src

jobs:
  # inpiration from https://www.cynkra.com/blog/2020-12-23-dynamic-gha/
  create-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Set Matrix
        id: set-matrix
        run: |
          matrix=$((
          echo '{ "config" : ['
          [[ "true" == "${{ inputs.windows }}" ]] && echo '{ "name": "Windows MSVC", "os": "windows-latest", "cc": "cl.exe", "cxx": "cl.exe", "icon": "Windows", "extra-flags": "" }'
          [[ "true" == "${{ inputs.windows }}" && "true" == "${{inputs.linux}}" ]] && echo ','
          [[ "true" == "${{ inputs.linux }}" ]] && echo '{ "name": "Ubuntu gcc", "os": "ubuntu-latest", "cc": "gcc", "cxx": "g++", "icon": "Linux", "extra-flags": "-DCMAKE_CXX_FLAGS=-Wno-deprecated-declarations -DRADIUM_ENABLE_GL_TESTING=ON" }'
          [[ "true" == "${{ inputs.windows }}" || "true" == "${{inputs.linux}}" ]] && [[ "true" == "${{inputs.macos}}" ]] && echo ','
          [[ "true" == "${{ inputs.macos }}" ]] && echo '{ "name": "MacOS clang", "os": "macos-13", "cc": "clang", "cxx": "clang++", "icon": "Apple", "extra-flags": "-DCMAKE_CXX_FLAGS=-Wno-deprecated-declarations" }'
          echo '],'
          echo '"build-type" : ['
          [[ "true" == "${{ inputs.build-debug }}" ]] && echo '"Debug"'
          [[ "true" == "${{ inputs.build-debug }}" && "true" == "${{ inputs.build-release }}" ]] && echo ','
          [[ "true" == "${{ inputs.build-release }}" ]] && echo '"Release"'
          echo '],'
          echo '"precision" : ['
          echo '{ "name": "float", "value": "OFF"}'
          [[ "true" == "${{ inputs.use-double }}" ]] && echo ', { "name": "double", "value": "ON" }'
          echo '],'
          echo '"qtversion" : [ { "name" : "qt6", "value" : "6.2.0"}],'
          echo '"coverage" : ['
          [[ "true" == "${{ inputs.coverage }}" ]] && echo '{ "value" : "ON", "extra-flags" : "-DRADIUM_ENABLE_GL_TESTING=ON" }' || echo '{ "value" : "OFF", "extra-flags" : "" }'
          echo "]"
          echo "}"
          ) | jq -c .)
          echo $matrix
          echo $matrix | jq .
          echo "matrix=$matrix" >> $GITHUB_OUTPUT

  check-matrix:
    runs-on: ubuntu-latest
    needs: create-matrix
    steps:
      - name: Install json2yaml
        run: |
          sudo npm install -g json2yaml
      - name: Check matrix definition
        run: |
          matrix='${{ needs.create-matrix.outputs.matrix }}'
          echo $matrix
          echo $matrix | jq .
          echo $matrix | json2yaml

  build:
    needs: create-matrix
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.create-matrix.outputs.matrix) }}
    steps:
      - name: Compute paths
        id: paths
        run: |
          radium_build_dir="${{ env.build_prefix }}/${{ matrix.build-type }}/Radium-Engine"
          radium_install_dir="${{ env.install_prefix }}/${{ matrix.build-type }}/Radium-Engine"
          external_build_dir="${{ env.build_prefix }}/${{ matrix.build-type }}/external"
          external_install_dir="${{ env.install_prefix }}/${{ matrix.build-type }}/external"
          echo "radium_build_dir=$radium_build_dir" >> $GITHUB_OUTPUT
          echo "radium_install_dir=$radium_install_dir" >> $GITHUB_OUTPUT
          echo "external_build_dir=$external_build_dir" >> $GITHUB_OUTPUT
          echo "external_install_dir=$external_install_dir" >> $GITHUB_OUTPUT

      - name: Add msbuild to PATH
        uses: seanmiddleditch/gha-setup-vsdevenv@master
        if: runner.os == 'Windows'

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          cache: true
          cache-key-prefix: install-qt-action-${{ matrix.config.name }}-${{ matrix.qtversion.value }}
          version: ${{ matrix.qtversion.value }}

      - name: Install dep Linux (normal, test, coverage)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libglfw3-dev libxml2-utils lcov
          pip3 install fastcov

      - name: Install dep MacOS
        if: runner.os == 'macOS'
        run: brew install glfw

      - name: Install dep windows checkout
        if: runner.os == 'Windows'
        uses: actions/checkout@v2
        with:
          repository: glfw/glfw
          ref: 3.4
          path: glfw

      - name: Build windows dep, config path
        if: runner.os == 'Windows'
        run: |
          posix_path=$(cygpath -u "${{ github.workspace }}")
          mkdir -p "$posix_path/glfw_install/"
          cmake -S glfw -B glfw/build-shared -G "Visual Studio 17 2022" -DBUILD_SHARED_LIBS=OFF \
          -DGLFW_BUILD_EXAMPLES=OFF -DGLFW_BUILD_TESTS=OFF -DGLFW_BUILD_DOCS=OFF \
          -DCMAKE_INSTALL_PREFIX="$posix_path/glfw_install/"
          cmake --build glfw/build-shared --parallel --config Release
          cmake --build glfw/build-shared --target install --config Release
          echo "glfw_path=-Dglfw3_DIR=$posix_path/glfw_install/lib/cmake/glfw3/" >> $GITHUB_ENV
          # Setting paths to dll needed by catch2 and run in build dir
          echo "$posix_path/glfw_install/lib" >> $GITHUB_PATH
          echo "$posix_path/${{ steps.paths.outputs.radium_build_dir }}/src/Core" >> $GITHUB_PATH
          echo "$posix_path/${{ steps.paths.outputs.radium_build_dir }}/src/Engine" >> $GITHUB_PATH
          echo "$posix_path/${{ steps.paths.outputs.radium_build_dir }}/src/Dataflow/Core" >> $GITHUB_PATH
          echo "$posix_path/${{ steps.paths.outputs.radium_build_dir }}/src/Dataflow/QtGui" >> $GITHUB_PATH
          echo "$posix_path/${{ steps.paths.outputs.radium_build_dir }}/src/Gui" >> $GITHUB_PATH
          echo "$posix_path/${{ steps.paths.outputs.radium_build_dir }}/src/Headless" >> $GITHUB_PATH
          echo "$posix_path/${{ steps.paths.outputs.radium_build_dir }}/src/IO" >> $GITHUB_PATH
          echo "$posix_path/${{ steps.paths.outputs.radium_build_dir }}/src/PluginBase" >> $GITHUB_PATH
          echo "$posix_path/${{ steps.paths.outputs.external_install_dir }}/bin" >> $GITHUB_PATH
          echo "$posix_path/${{ steps.paths.outputs.external_install_dir }}/glbinding" >> $GITHUB_PATH
          echo "$posix_path/${{ steps.paths.outputs.external_install_dir }}/globjects" >> $GITHUB_PATH
          echo "$posix_path/${{ steps.paths.outputs.external_install_dir }}/cpplocate" >> $GITHUB_PATH

      - name: Prepare directories
        run: |
          mkdir -p "${{ env.src_prefix }}"
          mkdir -p "${{ steps.paths.outputs.radium_build_dir }}"
          mkdir -p "${{ steps.paths.outputs.external_build_dir }}"
          mkdir -p "${{ steps.paths.outputs.radium_install_dir }}"
          mkdir -p "${{ steps.paths.outputs.external_install_dir }}"

      - name: Checkout remote head
        uses: actions/checkout@master
        with:
          path: ${{ env.src_prefix }}/Radium-Engine
          submodules: 'recursive'

      - name: pull updated repo (e.g. with new VERSION)
        if: ${{ github.event_name == 'push' }}
        run: |
          git -C "${{ env.src_prefix }}/Radium-Engine" pull origin ${{ github.event.ref }}
          git -C "${{ env.src_prefix }}/Radium-Engine" submodule update --init --recursive

      - name: Cache externals
        id: cache-external
        uses: actions/cache@v4
        with:
          path: ${{ steps.paths.outputs.external_install_dir }}
          key: ${{ matrix.config.name }}-${{ matrix.build-type }}-${{ matrix.qtversion.name }}-external-v1-${{ hashFiles('src/Radium-Engine/external/**/CMakeLists.txt') }} # no env in hashFiles

      - name: Configure and build external
        if: steps.cache-external.outputs.cache-hit != 'true'
        run: |
          "${{ env.src_prefix }}/Radium-Engine/scripts/build.sh" -e true -r false \
          -B "${{ env.build_prefix }}" -c ${{ matrix.build-type }} \
          -G Ninja --cc ${{ matrix.config.cc }} --cxx ${{ matrix.config.cxx }} \
          --install-external "${{ steps.paths.outputs.external_install_dir }}"

      - name: Configure and build Radium
        run: |
          "${{ env.src_prefix }}/Radium-Engine/scripts/build.sh" -e false -r true \
          -B "${{ env.build_prefix }}" -c ${{ matrix.build-type }} \
          -G Ninja --cc ${{ matrix.config.cc }} --cxx ${{ matrix.config.cxx }} \
          --install-external ${{ steps.paths.outputs.external_install_dir }} \
          --install-radium  "${{ steps.paths.outputs.radium_install_dir }}" \
          -o "${{ env.glfw_path }} ${{ matrix.config.extra-flags }} ${{ matrix.coverage.extra-flags }}" \
          --use-double ${{ matrix.precision.value }} --enable-coverage ${{ matrix.coverage.value }}

      - name: Run unit tests
        if: ${{ inputs.coverage == 'false' }}
        run: |
          cmake --build "${{ steps.paths.outputs.radium_build_dir }}" --parallel --config ${{ matrix.build-type }} --target check
          cmake --build "${{ steps.paths.outputs.radium_build_dir }}" --parallel --config ${{ matrix.build-type }} --target Install_CoreExample
          "${{ steps.paths.outputs.radium_install_dir }}/bin/CoreExample"

      - name: Extract ref for badges prefix
        if: always()
        run: |
          GITHUB_REF=${{ github.ref }}
          echo "branch=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT
        id: extract-branch

      - name: Update badge on merge (failure)
        if: ${{ failure() && inputs.generate-badges == 'true' }}
        uses: schneegans/dynamic-badges-action@v1.0.0
        with:
          auth: ${{ secrets.GIST_BADGES_TOKEN }}
          gistID: ${{ secrets.GIST_BADGES_SECRET }}
          filename: "${{ steps.extract-branch.outputs.branch }}.${{ matrix.config.os }}.${{ matrix.build-type }}.${{ matrix.precision.name }}.json"
          label: CI ${{ matrix.build-type }}  ${{ matrix.precision.name }}
          message: 'falling'
          namedLogo: ${{ matrix.config.icon }}
          logoColor: white
          color: CC1B1B

      - name: Update badge on merge (success)
        if: ${{ success() && inputs.generate-badges == 'true' }}
        uses: schneegans/dynamic-badges-action@v1.0.0
        with:
          auth: ${{ secrets.GIST_BADGES_TOKEN }}
          gistID: ${{ secrets.GIST_BADGES_SECRET }}
          filename: "${{ steps.extract-branch.outputs.branch }}.${{ matrix.config.os }}.${{ matrix.build-type }}.${{ matrix.precision.name }}.json"
          label: CI ${{ matrix.build-type }}  ${{ matrix.precision.name }}
          message: 'passing'
          namedLogo: ${{ matrix.config.icon }}
          logoColor: white
          color: 1BCC1B

      - name: Create coverage report
        if: ${{ inputs.coverage == 'true' }}
        run: |
          cmake --build "${{ steps.paths.outputs.radium_build_dir }}" --config Debug --target fastcov_integration
          cmake --build "${{ steps.paths.outputs.radium_build_dir }}" --config Debug --target fastcov_unittests

      - name: Upload unittests coverage report
        if: ${{ inputs.coverage == 'true' }}
        uses: codecov/codecov-action@v5
        with:
          fail_ci_if_error: true # optional (default = false)
          files: ${{ steps.paths.outputs.radium_build_dir }}/fastcov_unittests.info
          flags: unittests
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true # optional (default = false)
          disable_search: true

      - name: Upload integration coverage report
        if: ${{ inputs.coverage == 'true' }}
        uses: codecov/codecov-action@v5
        with:
          fail_ci_if_error: true # optional (default = false)
          files: ${{ steps.paths.outputs.radium_build_dir }}/fastcov_integration.info
          flags: integration
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true # optional (default = false)
          disable_search: true
