name: Create tag (notified from dispatch event)

defaults:
  run:
    shell: bash


on:
  repository_dispatch:
    types: [new-tag-event]

jobs:
  createTag:
    runs-on: ubuntu-latest
    steps:
      - name: Tag current head
        uses: tvdias/github-tagger@v0.0.1
        with:
          repo-token: "${{ secrets.REPO_DISPATCH_TOKEN }}"
          tag: "${{ github.event.client_payload.tagname }}"
